os:
    - linux
    - osx
matrix:
    allow_failures:
        - os: osx
language: python
python:
    - "3.0"
    - "3.1"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
install:
    - "pip install -r requirements-hacking.txt"
script: make unittest
