os:
    - linux
    - osx
matrix:
    allow_failures:
        - os: osx
language: python
python:
    - "3.4"
    - "3.5"
before install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git clone https://github.com/MacPython/terryfy; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source terryfy/travis_tools.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then get_python_environment homebrew $TRAVIS_PYTHON_VERSION; fi
install:
    - "pip install -r requirements-hacking.txt"
script: make unittest
